//! Compilation of ESS/runtime IR into the SDK-executable plan and generated Rust package.

use std::collections::BTreeMap;

use anyhow::{Result, anyhow, bail};
use ess_compiler::EssIr;
use ess_compiler::ir::{ResolvedCondition, ResolvedEffect, ResolvedPayloadValue};
use service_definition::{
    ContextValue, EventBindingSource, ExpectedVersionSource, IdempotencySource, RealmPolicy,
    StreamIdSource,
};
use service_engine::{
    ContentPolicyPlan, ContextSource, EventFieldPlan, ExpectedVersionPlan, IdempotencyPlan,
    InheritancePlan, InputPlan, InputSource, IntentPlan, ObligationUse, OutcomePlan,
    PlanRealmPolicy, ProducedEventPlan, QueryPlan, REALIZATION_PLAN_FORMAT, ReducerEffect,
    ReducerPlan, ServicePlan, StreamPlan, ValueSource, ViewPlan,
};
use service_runtime_ir::ServiceRuntimeIr;

use crate::client::{ClientInputSource, ClientOperationKind, ClientPlan};
use crate::package::SdkLock;

/// Generated compilable files added only for unified packages carrying exact dependency locks.
pub struct RealizationArtifacts {
    /// Relative artifact path to UTF-8 bytes.
    pub files: BTreeMap<String, String>,
}

impl RealizationArtifacts {
    /// Emits a service library, runtime constructor, client constants, and real Connector factory.
    pub fn generate(plan: &ServicePlan, _client: &ClientPlan, sdk: &SdkLock) -> Self {
        let crate_name = format!("{}-generated-service", plan.service.replace('_', "-"));
        let module_name = plan.service.replace('-', "_");
        let cargo = format!(
            "# generated by service-builder; do not edit\n\
[package]\nname = \"{crate_name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n\n\
[dependencies]\n\
service-engine = {{ git = \"{}\", rev = \"{}\" }}\n\
service-connectors = {{ git = \"{}\", rev = \"{}\" }}\n",
            sdk.repository, sdk.revision, sdk.repository, sdk.revision
        );
        let source = rust_source(&module_name);
        Self {
            files: BTreeMap::from([
                ("rust/Cargo.toml".to_owned(), cargo),
                ("rust/src/lib.rs".to_owned(), source),
            ]),
        }
    }
}

/// Compiles a complete executable plan, refusing semantic shapes the SDK cannot realize.
#[allow(clippy::too_many_lines)]
pub fn compile(
    ess: &EssIr,
    runtime: &ServiceRuntimeIr,
    client: &ClientPlan,
) -> Result<ServicePlan> {
    let definition = runtime.definition();
    let mut reducers = BTreeMap::new();
    let mut intents = BTreeMap::new();

    for (name, resolved) in runtime.intents() {
        let annotation = definition
            .intents
            .iter()
            .find(|item| item.name == *name)
            .ok_or_else(|| anyhow!("intent {name} lost its source annotation"))?;
        let client_operation = client
            .operations
            .iter()
            .find(|item| item.operation == name.as_str())
            .ok_or_else(|| anyhow!("intent {name} lost its generated client operation"))?;
        let command = ess
            .commands()
            .values()
            .find(|item| item.name.to_string() == resolved.command)
            .ok_or_else(|| anyhow!("resolved command {} is absent", resolved.command))?;
        let success = command
            .outcomes
            .iter()
            .filter(|outcome| matches!(outcome.condition, ResolvedCondition::Otherwise))
            .collect::<Vec<_>>();
        let [success] = success.as_slice() else {
            bail!(
                "command {} requires exactly one otherwise outcome for SDK realization; found {}",
                command.name,
                success.len()
            );
        };
        let mut produced = Vec::new();
        for event_handle in &success.emits {
            let event = ess.events().get(event_handle.name()).ok_or_else(|| {
                anyhow!("outcome event {event_handle} is absent from compiler IR")
            })?;
            let payload = success
                .payload
                .iter()
                .find(|payload| payload.event == *event_handle);
            let mut fields = Vec::new();
            for field in &event.fields {
                let payload_source = payload
                    .and_then(|payload| {
                        payload.fields.iter().find(|item| item.target == field.name)
                    })
                    .map(|field| match &field.value {
                        ResolvedPayloadValue::InputField { field, .. } => ValueSource::Input {
                            field: field.clone(),
                        },
                        ResolvedPayloadValue::Literal { value } => ValueSource::Literal {
                            value: value.clone(),
                        },
                    });
                let binding_source = annotation
                    .event_bindings
                    .iter()
                    .find(|binding| {
                        binding.event.name() == event_handle.name() && binding.field == field.name
                    })
                    .map(|binding| event_binding(runtime, &binding.source, &field.name))
                    .transpose()?;
                let source = match (payload_source, binding_source) {
                    (Some(_), Some(_)) => bail!(
                        "event {} field {:?} is derived by both ESS payload and runtime binding",
                        event.name,
                        field.name
                    ),
                    (Some(source), None) | (None, Some(source)) => source,
                    (None, None) => bail!(
                        "event {} field {:?} has no ESS payload or SDK event binding",
                        event.name,
                        field.name
                    ),
                };
                fields.push(EventFieldPlan {
                    name: field.name.clone(),
                    source,
                });
            }
            produced.push(ProducedEventPlan {
                event: event.name.to_string(),
                fields,
            });
        }

        let obligations = obligation_uses(runtime, &annotation.obligations)?;
        if let Some(subject) = &success.subject {
            let entity = ess.entity(&subject.entity);
            let inherit = obligations
                .iter()
                .find(|item| item.provider == "sdk.derive.inherit-parent-authority/v1")
                .map(inheritance)
                .transpose()?;
            let effect = match &subject.effect {
                ResolvedEffect::Creates => ReducerEffect::Create {
                    initial_state: entity.lifecycle.initial.to_string(),
                },
                ResolvedEffect::Updates => ReducerEffect::Update,
                ResolvedEffect::Moves { transition } => ReducerEffect::Move {
                    from: transition.from.iter().map(ToString::to_string).collect(),
                    to: transition.to.to_string(),
                },
            };
            let reducer = ReducerPlan {
                entity: entity.name.to_string(),
                identity_field: subject.instance.field().name.clone(),
                effect,
                fields: entity
                    .fields
                    .iter()
                    .map(|field| field.name.clone())
                    .collect(),
                inherit,
            };
            for event in &produced {
                match reducers.insert(event.event.clone(), reducer.clone()) {
                    Some(previous) if previous != reducer => {
                        bail!("event {} has incompatible reducer meanings", event.event)
                    }
                    _ => {}
                }
            }
        }

        intents.insert(
            name.to_string(),
            IntentPlan {
                command: resolved.command.clone(),
                inputs: input_plans(client_operation, annotation)?,
                stream: match &annotation.stream_id {
                    StreamIdSource::CommandField { field } => StreamPlan::CommandField {
                        field: field.clone(),
                    },
                    StreamIdSource::GeneratedUuidV7 => StreamPlan::GeneratedUuidV7,
                },
                expected_version: match &annotation.expected_version {
                    ExpectedVersionSource::NoStream => ExpectedVersionPlan::NoStream,
                    ExpectedVersionSource::OperationField { field } => {
                        ExpectedVersionPlan::OperationField {
                            field: field.clone(),
                        }
                    }
                },
                idempotency: match &annotation.idempotency {
                    IdempotencySource::OperationField { field } => {
                        IdempotencyPlan::OperationField {
                            field: field.clone(),
                        }
                    }
                    IdempotencySource::RequestId => IdempotencyPlan::RequestId,
                },
                obligations,
                outcome: OutcomePlan {
                    name: success.name.to_string(),
                    events: produced,
                },
                projections: annotation
                    .projections
                    .iter()
                    .map(ToString::to_string)
                    .collect(),
            },
        );
    }

    let mut queries = BTreeMap::new();
    for (name, resolved) in runtime.queries() {
        let annotation = definition
            .queries
            .iter()
            .find(|item| item.name == *name)
            .ok_or_else(|| anyhow!("query {name} lost its source annotation"))?;
        let client_operation = client
            .operations
            .iter()
            .find(|item| item.operation == name.as_str())
            .ok_or_else(|| anyhow!("query {name} lost its generated client operation"))?;
        queries.insert(
            name.to_string(),
            QueryPlan {
                view: resolved.view.clone(),
                inputs: input_plans_query(client_operation)?,
                obligations: obligation_uses(runtime, &annotation.obligations)?,
            },
        );
    }

    let mut views = BTreeMap::new();
    for projection in runtime.projections().values() {
        let annotation = definition
            .projections
            .iter()
            .find(|item| item.view.to_string() == projection.view)
            .ok_or_else(|| anyhow!("projection {} lost its source annotation", projection.view))?;
        let view = ess
            .views()
            .values()
            .find(|view| view.name.to_string() == projection.view)
            .ok_or_else(|| anyhow!("projection view {} is absent", projection.view))?;
        views.insert(
            projection.view.clone(),
            ViewPlan {
                source: view.source.to_string(),
                fields: view.fields.iter().map(|field| field.name.clone()).collect(),
                obligations: obligation_uses(runtime, &annotation.obligations)?,
            },
        );
    }

    Ok(ServicePlan {
        format: REALIZATION_PLAN_FORMAT.to_owned(),
        service: definition.service.to_string(),
        realm: match definition.realm {
            RealmPolicy::Required => PlanRealmPolicy::Required,
            RealmPolicy::Optional => PlanRealmPolicy::Optional,
            RealmPolicy::Forbidden => PlanRealmPolicy::Forbidden,
        },
        ess_source_digest: runtime.ess_source_digest().to_owned(),
        obligation_catalog_digest: runtime.obligation_catalog_digest().to_owned(),
        content: definition
            .content
            .iter()
            .map(|policy| {
                (
                    policy.name.to_string(),
                    ContentPolicyPlan {
                        media_types: policy.media_types.iter().cloned().collect(),
                        max_bytes: policy.max_bytes,
                    },
                )
            })
            .collect(),
        intents,
        queries,
        reducers,
        views,
    })
}

fn input_plans(
    client: &crate::client::ClientOperation,
    intent: &service_definition::IntentDefinition,
) -> Result<Vec<InputPlan>> {
    if client.kind != ClientOperationKind::Intent {
        bail!("client operation {} is not an intent", client.operation);
    }
    client
        .inputs
        .iter()
        .map(|input| {
            let source = match &input.source {
                ClientInputSource::Command => InputSource::Command,
                ClientInputSource::ExpectedVersion => InputSource::ExpectedVersion,
                ClientInputSource::Idempotency => InputSource::Idempotency,
                ClientInputSource::Content { policy } => {
                    let binding = intent
                        .content
                        .iter()
                        .find(|binding| binding.content.as_str() == policy)
                        .ok_or_else(|| anyhow!("content input {} lost its binding", input.name))?;
                    InputSource::Content {
                        policy: policy.clone(),
                        command_field: binding.command_reference_field.clone(),
                    }
                }
                ClientInputSource::Selector { .. } => {
                    bail!("intent {} contains a query selector", client.operation)
                }
            };
            Ok(InputPlan {
                name: input.name.clone(),
                type_ref: input.type_ref.clone(),
                optional: input.optional,
                source,
            })
        })
        .collect()
}

fn input_plans_query(client: &crate::client::ClientOperation) -> Result<Vec<InputPlan>> {
    if client.kind != ClientOperationKind::Query {
        bail!("client operation {} is not a query", client.operation);
    }
    client
        .inputs
        .iter()
        .map(|input| {
            let ClientInputSource::Selector { view_field } = &input.source else {
                bail!("query {} has a non-selector input", client.operation);
            };
            Ok(InputPlan {
                name: input.name.clone(),
                type_ref: input.type_ref.clone(),
                optional: input.optional,
                source: InputSource::Selector {
                    view_field: view_field.clone(),
                },
            })
        })
        .collect()
}

fn obligation_uses(
    runtime: &ServiceRuntimeIr,
    references: &[service_definition::DefinitionId],
) -> Result<Vec<ObligationUse>> {
    references
        .iter()
        .map(|reference| {
            let resolved = runtime
                .obligations()
                .get(reference)
                .ok_or_else(|| anyhow!("obligation {reference} is unresolved"))?;
            Ok(ObligationUse {
                provider: resolved.provider.to_string(),
                bindings: resolved
                    .bindings
                    .iter()
                    .map(|(name, value)| (name.to_string(), value.clone()))
                    .collect(),
            })
        })
        .collect()
}

fn event_binding(
    runtime: &ServiceRuntimeIr,
    source: &EventBindingSource,
    target: &str,
) -> Result<ValueSource> {
    Ok(match source {
        EventBindingSource::StreamId => ValueSource::StreamId,
        EventBindingSource::CommandField { field } => ValueSource::Input {
            field: field.clone(),
        },
        EventBindingSource::Context { value } => ValueSource::Context {
            value: match value {
                ContextValue::TenantId => ContextSource::TenantId,
                ContextValue::RealmIdOptional => ContextSource::RealmIdOptional,
                ContextValue::UserId => ContextSource::UserId,
                ContextValue::CurrentAuthority => ContextSource::CurrentAuthority,
                ContextValue::ExecutorOptional => ContextSource::ExecutorOptional,
            },
        },
        EventBindingSource::GeneratedUuidV7 => ValueSource::GeneratedUuidV7,
        EventBindingSource::Obligation { name } => {
            let obligation = runtime
                .obligations()
                .get(name)
                .ok_or_else(|| anyhow!("event binding obligation {name} is unresolved"))?;
            let (entity_binding, field_binding) = if target.contains("scope") {
                ("parent", "parent_scopes")
            } else {
                ("parent", "parent_owner")
            };
            let entity = obligation
                .bindings
                .iter()
                .find(|(name, _)| name.as_str() == entity_binding)
                .map(|(_, value)| value.clone())
                .ok_or_else(|| anyhow!("event binding obligation {name} lacks {entity_binding}"))?;
            let source_field = obligation
                .bindings
                .iter()
                .find(|(name, _)| name.as_str() == field_binding)
                .map(|(_, value)| value)
                .and_then(|path| path.rsplit_once('.').map(|(_, field)| field.to_owned()))
                .ok_or_else(|| anyhow!("event binding obligation {name} lacks {field_binding}"))?;
            ValueSource::Obligation {
                provider: obligation.provider.to_string(),
                entity,
                field: source_field,
            }
        }
    })
}

fn inheritance(obligation: &ObligationUse) -> Result<InheritancePlan> {
    let required = |name: &str| {
        obligation
            .bindings
            .get(name)
            .cloned()
            .ok_or_else(|| anyhow!("{} lacks {name}", obligation.provider))
    };
    let field = |name: &str| -> Result<String> {
        let path = required(name)?;
        Ok(path
            .rsplit_once('.')
            .map_or(path.clone(), |(_, field)| field.to_owned()))
    };
    Ok(InheritancePlan {
        parent: required("parent")?,
        parent_owner: field("parent_owner")?,
        parent_scopes: field("parent_scopes")?,
        child_owner: field("child_owner")?,
        child_scopes: field("child_scopes")?,
    })
}

fn rust_source(module_name: &str) -> String {
    format!(
        r#"// generated by service-builder; do not edit
//! Complete generated service and Connector contribution for `{module_name}`.

#![forbid(unsafe_code)]

use std::sync::Arc;

/// Exact generated runtime realization plan.
pub const REALIZATION_PLAN_JSON: &str = include_str!("../../runtime/realization-plan.json");

/// Exact generated, realm-free Connector catalog contribution.
pub const CONNECTOR_CONTRIBUTION_JSON: &str = include_str!("../../connectors/contribution.json");

/// Constructs the SDK-owned executor; deployment injects only resource adapters.
pub fn service() -> Result<service_engine::ServiceEngine, service_engine::PlanError> {{
    service_engine::ServicePlan::from_json(REALIZATION_PLAN_JSON)
        .map(service_engine::ServiceEngine::new)
}}

/// SDK-owned generated Connector factory. Applications cannot replace its backend behavior.
pub type ConnectorFactory = service_connectors::GeneratedConnectorFactory;

/// Creates the operational factory from generated data and a deployment-selected Eventlog store.
pub fn connector_factory(
    store: Arc<dyn service_connectors::DurableEventStore>,
) -> Result<ConnectorFactory, service_connectors::GeneratedFactoryError> {{
    ConnectorFactory::from_json(REALIZATION_PLAN_JSON, CONNECTOR_CONTRIBUTION_JSON, store)
}}
"#,
    )
}
